### PR TITLE
Update 3.md

### PR DESCRIPTION
**Pull request by khawla-k-banydomi**
# Entrega del hito 3 de Cloud Computing

Corresponde al hito 3

## Primero y más importante

* [x] Prometo no cerrar *nunca* un PR, enviar sólo uno por hito, y no abrir 
 nuevos si este no funciona.

## Lista de comprobación para hitos

* [x] He leído el guión del hito
* [x] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x] He actualizado con la última versión del fichero de entrega (y resto del
      repositorio).
* [ ] Marca esto si no estás leyendo lo que estás marcando.
* [ ] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.

### CODE REVIEW

**Comment by JJ** [comment]
I'm cancelling this workflow so that it does not take several hours again like the last one. It's failing anyway another test.

**Comment by JJ** [comment]
1. You have to change *the version*
2. You have to indicate that this is a revision, as you have marked.
3. You have to use *the same GitHub nick as is in your slot*. You can't simply change the GitHub identifier to an unknown one during the project.
4. If the docker container takes more than 5 minutes, I'll cancel this.

**Comment by JJ** [comment]
Cancelled. The docker container does not even do what this milestone requests. It starts a server.

**Comment by JJ** [comment]
Again, I've had to cancel 2 workflows that had been running for 30 and 17 minutes. *Please* don't do this again. The container you're submitting does not do what it's supposed to do in this milestone, and long-running times run the risk of exhausting our credit which will make Github ban us from running any other github action. Please don't make any more PRs until you fix that Dockerfile to follow what this assignment says (which is run a test, not run a REST server).

**Comment by JJ** [comment]
You can't update two files in the same PR.

**Comment by khawla-k-banydomi** [comment]
@JJ yes my professor; I notice this...I create another branch and try to compare and make a PR

**Comment by JJ** [comment]
Milestone 4 is going to run tests for milestone 3 also. Until you pass those, I don't see any point in creating yet another PR that will fail.

**Pull request closed without merging**
