### PR TITLE
Update 1.md

### PR DESCRIPTION
**Pull request by khawla-k-banydomi**
# Entrega del hito *1* de Cloud Computing

Corresponde al hito <1>

## Primero y más importante

* [x] Prometo no cerrar *nunca* un PR, enviar sólo uno por hito, y no abrir 
 nuevos si este no funciona.

## Lista de comprobación para hitos

* [x] He leído el guión del hito
* [x] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x] He actualizado con la última versión del fichero de entrega (y resto del
      repositorio).
* [ ] Marca esto si no estás leyendo lo que estás marcando.
* [x] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.

### CODE REVIEW

**Comment by JJ** [comment]
You really need to pay attention to errors and resubmit.

**Comment by khawla-k-banydomi** [comment]
@JJ my professor it askes me to have cc.yaml

**Comment by JJ** [comment]
Not only

**Comment by khawla-k-banydomi** [comment]
I see that it is a must to have open issues for the user stories till it is completely clarified.. I will fix this my professor

**Comment by JJ** [comment]
And yes, it asks precisely [what's in the description of this milestone](http://jj.github.io/CC/documentos/proyecto/2021/1.Infraestructura)

**Comment by khawla-k-banydomi** [comment]
@JJ my professor I modify it and still has the same errors

**Comment by JJ** [comment]
Well, that is correct. If you don't fix the problem in your repo, you will still get the same errors.

**Review by JJ — APPROVED** [review]
:+1:

**Comment by JJ** [comment]
Why are you updating and lowering the version?

**Comment by khawla-k-banydomi** [comment]
I am so sorry for doing this my professor..I will modify this

**Comment by JJ** [comment]
Just don't touch anything. This has been already approved, and is waiting for the professor of this class (not me anymore) to merge. Just be patient.

**Comment by khawla-k-banydomi** [comment]
Thanks my professor for your guidance..

**Comment by khawla-k-banydomi** [comment]
Dear my professor;
 till now I am still waiting ...what should I do now...no time remaining..

**Comment by JJ** [comment]
Waiting for what? It's been graded and the grade is in the shared document for several days. Also, nobody said you couldn't send all milestones without waiting for the grade.

**Comment by JJ** [comment]
If you're waiting for it to be merged, I'm no longer the professor of this class. I can't do that any more.

**Comment by khawla-k-banydomi** [comment]
can I resubmit please?

**Comment by JJ** [comment]
There's no possibility of resubmission in this case, I'm sorry. You'll have to fix many of the things said there in the next milestone anyway.

**Comment by khawla-k-banydomi** [comment]
how can I continue the submissions without it would be merged.. 2 PR will close the PR

**Comment by khawla-k-banydomi** [comment]
@jj In this project I’ve used functional programming which uses Schema instead of classes but its the samething..you told me that I dont have to use schema ..what I should use instead..

**Comment by JJ** [comment]
> @JJ In this project I’ve used functional programming which uses Schema instead of classes but its the samething..you told me that I dont have to use schema ..what I should use instead..

No, I didn't tell you that. And you problably mean [Scheme](https://en.wikipedia.org/wiki/Scheme_(programming_language)), not [(JSON) Schema](https://json-schema.org/), which has nothing to do with functional programming and is not even part of the standard library (which means your code does not actually compile).

**Comment by JJ** [comment]
@khawla-k-banydomi by now you should know how to open a second PR without adding the changes to the previous one. Now we can't merge this one because it's errored, and the tests for the second milestone have not passed. Please revert the last change, and submit changes in a different PR.

**Comment by khawla-k-banydomi** [comment]
@JJ thanks my professor ..I will try doing these things.

**Pull request closed without merging**
